### ISSUE TITLE
AttributeError: module 'pyIRDecoder' has no attribute 'IRDecoder' on launching example.py

### ISSUE THREAD

**Issue by verylastnick** [kdschlosser/pyIRDecoder#1]
Hi Kevin,
I was very much looking forward to use your decoder. On running example.py and the brief python code from your readme.md I always get the error message: 
```
Traceback (most recent call last):
  File "C:\pyIRDecoder-master\example.py", line 36, in <module>
    ir_decoder = pyIRDecoder.IRDecoder()
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyIRDecoder' has no attribute 'IRDecoder'
```
I tried to fix it without success. I could not find an atribute IRDecoder while searching in the source files.
Is there something I am missing out?

**Comment by zhoumingwu** [comment]
Tell me, have you resolved it now?

**Comment by verylastnick** [comment]
> Tell me, have you resolved it now?

Hi zhoumingwu, no I did'nt. I have'nt tried any further after posting this issue.

**Comment by verylastnick** [comment]
> Tell me, have you resolved it now?

I just saw, that there is a "new" commit and pull request by jdk from 1. May 2023 which was build to fix the problem in the example.py. You might wanne give that a try.

**Comment by kdschlosser** [comment]
it's fixed.

**Comment by verylastnick** [comment]
Great! I just tried and it works like a charm! Thanks a bunch!
